#!/bin/bash

# See https://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests
if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    gem install jekyll;
    jekyll build;
fi
